#ifndef MVASPIKE_H
#define MVASPIKE_H
    
#define INF HUGE_VAL
    
#include <alltoall.h>
#include <basecoupled.h>
#include <baserecorder.h>
#include <clock.h>
#include <connections.h>
#include <containercoupled.h>
#include <coupled.h>
#include <dconnections.h>
#include <dcoupled.h>
#include <devs.h>
#include <devsiterator.h>
#include <error.h>
#include <event.h>
#include <eventiterator.h>
#include <extspiketrain.h>
#include <flatten_in.h>
#include <flatten_out.h>
#include <flow.h>
#include <freecon.h>
#include <freedcon.h>
#include <iface.h>
#include <ifacebase.h>
#include <internal_lif.h>
#include <ipoisson.h>
#include <lif.h>
#include <log_encoder.h>
#include <memspikerecorder.h>
#include <models.h>
#include <neuron.h>
#include <one_shot.h>
#include <phase.h>
#include <poisson.h>
#include <pq.h>
#include <pqf.h>
#include <pqf_heap.h>
#include <random.h>
#include <recorder.h>
#include <rng.h>
#include <rng_gsl_mt.h>
#include <rng_libc.h>
#include <rng_simple.h>
#include <root.h>
#include <sensor.h>
#include <simpledconnection.h>
#include <simpleiface.h>
#include <simplenet.h>
#include <spikerecorder.h>
#include <spiketrain.h>
#include <spiketrains.h>
#include <spontaneous.h>
#include <stdp.h>
#include <stdp2.h>
#include <stdp_rbt.h>
#include <stdpexp.h>
#include <stdpf.h>
#include <stdplif.h>
#include <streamspiketrains.h>
#include <warray.h>
#include <weightedinput.h>
#include <wstatic.h>
#endif
